#! /bin/sh

bspc config border_width        0
bspc config window_gap          6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding		23

tint3 &
compoton &

case `hostname` in
  "KOCHANSKI")
    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc monitor DVI-D-0 -d I II III
    bspc monitor HDMI-0 -d IV V VI VII
    bspc monitor DVI-I-1 -d VIII IX X
    ;;
  "ARCHY")
    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc monitor DVI-D-1 -d I II III
    bspc monitor HDMI-0 -d IV V VI VII
    bspc monitor DVI-I-0 -d VIII IX X
    ;;
esac

feh --bg-scale ~/.config/awesome/brilliant/background.jpg

bspc rule -a Chromium desktop=^2
