#! /bin/sh

bspc config border_width        0
bspc config window_gap          6
bspc config click_to_focus true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding	23

case `hostname` in
  "KOCHANSKI")
    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc monitor DVI-D-0 -d I II III
    bspc monitor HDMI-0 -d IV V VI VII
    bspc monitor DVI-I-1 -d VIII IX X

    tint3 -c ~/.tint3rc.KOCHANSKI.center &
    tint3 -c ~/.tint3rc.KOCHANSKI.left &
    tint3 -c ~/.tint3rc.KOCHANSKI.right &
    ;;
  "ARCHY")
    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc monitor DVI-D-1 -d I II III
    bspc monitor HDMI-0 -d IV V VI VII
    bspc monitor DVI-I-0 -d VIII IX X

    tint3 &
    ;;
esac

compoton &

feh --bg-max --no-xinerama ~/.config/background

bspc rule -a Chromium desktop=^2
