#! /bin/bash

bspc config border_width        0
bspc config window_gap          5
bspc config click_to_focus      true
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

HOSTNAME=`hostname`

polybar $HOSTNAME &

case $HOSTNAME in
  "KOCHANSKI")
    xrandr --output DVI-I-1 --mode 1920x1080 --pos 0x0      --rotate left \
           --output HDMI-0  --mode 1920x1080 --pos 1080x300 --rotate normal --primary \
           --output DVI-D-0 --mode 1920x1080 --pos 3000x0   --rotate right

    # Rename monitors
    bspc monitor DVI-D-0 -n right
    bspc monitor HDMI-0 -n center
    bspc monitor DVI-I-1 -n left

    bspc monitor left -d I II III
    bspc monitor center -d IV V VI VII
    bspc monitor right -d VIII IX X

    bspc config -m left top_padding 5
    bspc config -m left bottom_padding 5
    ;;
  "QUEEG500")
    bspc monitor -d I II III IV V VI VII VIII IX X

    xbindkeys
    ;;
  "ARCHY")
    xrandr --output DVI-I-1 --mode 1920x1080 --pos 0x0 --primary \
            --output VGA-1   --mode 1920x1080 --pos 1920x0

    bspc monitor DVI-I-1 -n primary
    bspc monitor VGA-1 -n secondary

    bspc monitor primary -d I II III IV V
    bspc monitor secondary -d VI VII VIII IX X
    bspc config -m secondary top_padding 5
    bspc config -m secondary bottom_padding 5
    ;;
esac

feh --bg-tile --no-xinerama ~/.config/background
