#! /bin/bash

bspc config border_width        0
bspc config window_gap          5
bspc config click_to_focus      true
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

HOSTNAME=`hostname`

case $HOSTNAME in

  # Desktop
  "KOCHANSKI")
    bspc monitor -d I II III IV V VI VII VIII IX X

    feh --bg-tile --no-xinerama ~/.config/background
    bspc rule -a 'mpv:docked' state=floating sticky=true rectangle=960x540+1600+900
    bspc rule -a 'Minecraft*:*' state=float center=true rectangle=1920x1080+320+180
    bspc rule -a 'Steam:*- Properties' state=float center=true
    ;;

  # Laptop
  "QUEEG500")
    bspc monitor -d I II III IV V VI VII VIII IX X

    feh --bg-scale  --no-xinerama ~/.config/background
    ;;

  # Work
  "ARCHY")
    xrandr --output DP-3 --mode 1920x1080 --pos 1080x220 --rotate normal --primary \
           --output DP-1 --mode 1920x1080 --pos 0x0      --rotate left

    bspc monitor DP-3 -n primary
    bspc monitor DP-1 -n secondary

    bspc monitor secondary -d I II III
    bspc monitor primary -d IV V VI VII VIII IX X

    bspc config -m secondary top_padding 5
    bspc config -m secondary bottom_padding 5

    feh --bg-tile --no-xinerama ~/.config/background
    ;;
  "*")
    ;;
esac

bspc rule -a firefox 'desktop=^2'
bspc rule -a Google-chrome 'desktop=^3'
bspc rule -a code-oss 'desktop=^4'
bspc rule -a Virt-manager 'desktop=^9'
bspc rule -a Slack 'desktop=^0'

polybar $HOSTNAME &

compton --vsync --no-fading-openclose &

sxhkd -s /tmp/sxhkd.fifo &
